// client/components/templates/LoginPage.vue
<template>
    <section class="page-container">
        <div class="teste">
            <Logo></Logo>
            <TitleForm title="Acesse sua conta"></TitleForm>
            <LoginForm></LoginForm>
        </div>
        <ImgLogin></ImgLogin>
    </section>
</template>

<script>
    import ImgLogin from '../atoms/ImgLogin.vue';
    import Logo from '../atoms/Logo.vue';
    import TitleForm from '../atoms/TitleForm.vue';
    import LoginForm from '../organisms/LoginForm.vue';
    export default {
        components: {
            ImgLogin,
            Logo,
            TitleForm,
            LoginForm
        }

    }
</script>

<style>
    .page-container {
        height: 100vh;
        width: 100%;
        display: flex;
    }

    .teste {
        height: 100vh;
        width: 50%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
</style>

// client/src/components/templates/LoginPage/LoginPage.jsx
import React from 'react'
import { Logo } from '../../atoms/Logo/Logo'
import { BackgroundLogin } from '../../atoms/BackgroundLogin/BackgroundLogin'
import { LoginForm } from '../../organisms/LoginForm/LoginForm'
import { TitleForm } from '../../atoms/TitleForm/TitleForm'
import './LoginPage.css'



export const LoginPage = () => {
  return (
    <section className="page-container">
        <div className="login-area">
           <Logo/>
           <TitleForm  title="Acesse sua conta"/>
           <LoginForm/>
        </div>
        <BackgroundLogin></BackgroundLogin>
    </section>
  )
}
